sudo: required
services:
  - docker
script:
  - docker build -t frontsiembra .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag frontsiembra $DOCKER_USER/frontsiembra:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/frontsiembra:$TRAVIS_BUILD_NUMBER
  - docker tag frontsiembra $DOCKER_USER/frontsiembra:latest
  - docker push $DOCKER_USER/frontsiembra:latest